---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb <- nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(borough = neighbourhood_group) |> 
  select(borough, neighbourhood, stars, price, room_type, 
         long, lat) |> 
  drop_na(stars)
  
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choices = nyc_airbnb |> 
  distinct(borough) |> 
  pull(borough)

selectInput(
  inputId = "borough_choice", 
  label = "Select Borough",
  choices = borough_choices, selected = "Manhattan"
)
```

```{r}
min_price <- nyc_airbnb |>  pull(price) |> min()
max_price <- nyc_airbnb |>  pull(price) |> max()

sliderInput(
  inputId = "price_range", 
  label = h3("Select Price Range"),
  min = min_price, 
  max = max_price, 
  value = c(100, 400)
)
```

```{r}
room_type = nyc_airbnb |> 
  distinct(room_type) |> 
  pull(room_type)

radioButtons(
  inputId = "room_choice", 
  label = "Select Room Type", 
  choices = room_type, 
  selected = "Entire home/apt"
)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Airbnb listing with their prices

```{r}
renderPlotly(
  nyc_airbnb |> 
  filter(borough == input[["borough_choice"]], 
         price %in% input[["price_range"]][1]:input[["price_range"]][2], 
         room_type == input[["room_choice"]]) |> 
  plot_ly(x = ~long, y =~lat, type = "scatter", mode = "markers", 
          alpha = 0.5, color = ~price)
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Airbnb prices by Neughborhood

```{r}
renderPlotly(
  nyc_airbnb |> 
  filter(borough == input[["borough_choice"]], 
         room_type == input[["room_choice"]]) |> 
    count(neighbourhood) |> 
    mutate(neighbourhood = fct_reorder(neighbourhood, n, .desc = TRUE)) |> 
  plot_ly(x = ~neighbourhood, y =~n, type = "bar")
)
```

### Price Distribution in Each Neighborhood

```{r}
renderPlotly(
  nyc_airbnb |> 
  filter(borough == input[["borough_choice"]], 
         price %in% input[["price_range"]][1]:input[["price_range"]][2], 
         room_type == input[["room_choice"]]) |> 
    mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(x = ~neighbourhood, y =~price, type = "box")
)
```